// Mocks generated by Mockito 5.0.16 from annotations
// in space_app/test/domain/usecases/get_mars_picture_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:space_app/core/error/failures.dart' as _i5;
import 'package:space_app/features/space_feature/domain/entities/mars_picture.dart'
    as _i7;
import 'package:space_app/features/space_feature/domain/entities/picture_of_the_day.dart'
    as _i6;

import 'get_mars_picture_test.dart' as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [MockNasaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockNasaRepository extends _i1.Mock
    implements _i3.MockNasaRepository {
  MockMockNasaRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String toString() => super.toString();
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.PictureOfTheDay>>
      getPictureOfTheDay() => (super.noSuchMethod(
              Invocation.method(#getPictureOfTheDay, []),
              returnValue:
                  Future<_i2.Either<_i5.Failure, _i6.PictureOfTheDay>>.value(
                      _FakeEither_0<_i5.Failure, _i6.PictureOfTheDay>()))
          as _i4.Future<_i2.Either<_i5.Failure, _i6.PictureOfTheDay>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.MarsPicture>> getMarsPicture(
          {String? cameraType}) =>
      (super.noSuchMethod(
          Invocation.method(#getMarsPicture, [], {#cameraType: cameraType}),
          returnValue: Future<_i2.Either<_i5.Failure, _i7.MarsPicture>>.value(
              _FakeEither_0<_i5.Failure, _i7.MarsPicture>())) as _i4
          .Future<_i2.Either<_i5.Failure, _i7.MarsPicture>>);
}
